In [1]:
import pandas as pd
from glob import glob

In [10]:
%run reusable_func.ipynb

In [6]:
spar_dir = "SQL_Data/Spar"
file_paths = glob(f"{spar_dir}/*.xlsx")

for file_path in file_paths:
    print(file_path)

SQL_Data/Spar/Copy of Insights Report_Ice Tea_Feb'24 (003).xlsx
SQL_Data/Spar/Copy of Insights Report_Ice Tea_Mar'24.xlsx
SQL_Data/Spar/Copy of Insights Report_Ice Tea_Apr'24.xlsx

In [7]:
# Read Spar Data:
# spar_path = "SQL_Data/Spar/Copy of Insights Report_Ice Tea_Mar'24.xlsx"#"SQL_Data/Spar/*.xlsx"
# spar_df = read_excel_file(spark, spar_path, sheet_name=None, sheet_index=0)
# spar_df = rename_columns(spar_df)

In [3]:
# Read Spar Data:
spar_all_df = read_all_excel_files(spar_dir, sheet_index=0)
spar_all_df = rename_columns(spar_all_df)
spar_all_df.show()

In [4]:
# Path to your Excel file
excel_path = "SQL_Data/Spar/Copy of Insights Report_Ice Tea_Apr'24.xlsx"

# Specify the sheet index (0-based)
sheet_index = 0  # Assuming the sheet you want is the first one

# Read the data from the specified sheet
df = pd.read_excel(excel_path, sheet_name=sheet_index)

# Now you can work with the DataFrame 'df'
df.head()

,Month-Yr,Region,Cluster,Barcode,Product - Size,Segment,Brand,Store,Format,Sales (R)\n2024,Sales (R)\n2023,Units\n2024,Units\n2023,Sales\nGwth,Units\nGwth
0,2024-04-01 00:00:00,NR,CL2,7.371861e+11,MOYA KOMBUCHA PINEAPPLE - 500MLT,ICED TEA,OTHER,SAFI SPAR,SPAR,293.79,391.72,21.0,28.0,-0.25,-0.25
1,2024-04-01 00:00:00,NR,CL2,7.371861e+11,MOYA KOMBUCHA PINEAPPLE - 1LTR,ICED TEA,OTHER,SAFI SPAR,SPAR,143.94,263.89,6.0,11.0,-0.454545,-0.454545
2,2024-04-01 00:00:00,NR,CL2,6.001651e+12,EJ S KOMBUCHA RAW - 500MLT,ICED TEA,OTHER,BARCLAY SQUARE SPAR,SPAR,349.86,191.92,14.0,8.0,0.822947,0.75
3,2024-04-01 00:00:00,NR,CL2,6.001651e+12,EJ S KOMBUCHA SPICY - 500MLT,ICED TEA,OTHER,BARCLAY SQUARE SPAR,SPAR,174.93,23.99,7.0,1.0,6.291788,6
4,2024-04-01 00:00:00,NR,CL2,6.001651e+12,EJ S KOMBUCHA BUCHU - 500MLT,ICED TEA,OTHER,BARCLAY SQUARE SPAR,SPAR,174.93,263.89,7.0,11.0,-0.33711,-0.363636

In [1]:
# spark_df = spark.createDataFrame(df)
# spark_df = rename_columns(spark_df)
# spark_df.show()

In [6]:
print(spar_all_df.count())

66620

In [7]:
from glob import glob
# from functools import reduce
# from pyspark.sql.functions import lit

def read_excel_files_count(spark, directory_path, sheet_name=None, sheet_index=0):
  """
  Reads all Excel files in a directory using PySpark.

  Args:
      spark (SparkSession): The SparkSession object.
      directory_path (str): The path to the directory containing Excel files.
      sheet_name (str, optional): The name of the sheet to read (default: None).
      sheet_index (int, optional): The zero-based index of the sheet to read (default: 0).

  Returns:
      list: A list of DataFrames, each corresponding to a single Excel file.
  """


  # Get all file paths in the directory
  file_paths = glob(f"{directory_path}/*.xlsx")  # Assuming .xlsx extension

  # Read each file using the original function and append to a list
  df = None
  for file_path in file_paths:
    df = read_excel_file(spark, file_path, sheet_name, sheet_index)
    print(df.count())
  #   if df is None:
  #     df = df_temp
  #   else:
  #     df = df.union(df_temp)

  #return dfs

In [8]:
from pyspark.sql.types import StructType, StructField

# Get the Spark dataframe schema
schema = spar_all_df.schema

# Convert the Spark schema to a Python structfield schema
spar_schema = StructType([StructField(field.name, field.dataType, field.nullable) for field in schema.fields])

# Print the Python structfield schema
print(spar_schema)

StructType([StructField('Month_Yr', TimestampType(), True), StructField('Region', StringType(), True), StructField('Cluster', StringType(), True), StructField('Barcode', StringType(), True), StructField('Product___Size', StringType(), True), StructField('Segment', StringType(), True), StructField('Brand', StringType(), True), StructField('Store', StringType(), True), StructField('Format', StringType(), True), StructField('Sales_(R)_2024', DoubleType(), True), StructField('Sales_(R)_2023', DoubleType(), True), StructField('Units_2024', DoubleType(), True), StructField('Units_2023', DoubleType(), True), StructField('Sales_Gwth', DoubleType(), True), StructField('Units_Gwth', DoubleType(), True), StructField('file_path', StringType(), False)])


To connect to a azure database need the connect:
`pip install com.microsoft.azure:spark-mssql-connector`
or 
`conda install -c microsoft com.microsoft.azure:spark-mssql-connector`
and `pip install pyspark pyodbc`

In [15]:
spark.stop()

In [ ]:
#Imports
#from pyspark import SparkConf
from pyspark.sql import SparkSession

In [ ]:
# Create a Spark session


spark = SparkSession.builder \
    .appName("WriteToSQLServer") \
    .config("spark.executor.memory", "6g") \
    .config("spark.driver.memory", "6g") \
    .config("spark.executor.cores", "4") \
    .config("spark.executor.extraJavaOptions", "-XX:+UseG1GC") \
    .config("spark.driver.extraJavaOptions", "-XX:+UseG1GC") \
    .config("spark.jars.packages", "com.microsoft.azure:spark-mssql-connector_2.12:1.1.0")\
    .getOrCreate() # .config("spark.sql.shuffle.partitions", "100") \

# """
# The parallel collector will throw an OutOfMemoryError if too much time is being spent in garbage collection: 
# if more than 98% of the total time is spent in garbage collection and less than 2% of the heap is recovered, 
# an OutOfMemoryError will be thrown. This feature is designed to prevent applications from running for an extended 
# period of time while making little or no progress because the heap is too small.
# If necessary, this feature can be disabled by adding the option -XX:-UseGCOverheadLimit to the command line.
# """

In [13]:
server_name = "jdbc:sqlserver://retailers.database.windows.net"
database_name = "consulting_db"
url = server_name + ";" + "databaseName=" + database_name + ";"

table_name = "staging.retailer_test"
username = "Bos"
password = "B@sNat0sh123!"

try:
  spar_all_df.write \
    .format("com.microsoft.sqlserver.jdbc.spark") \
    .mode("overwrite") \
    .option("url", url) \
    .option("dbtable", table_name) \
    .option("user", username) \
    .option("password", password) \
    .save()
except ValueError as error :
    print("Connector write failed", error)

Py4JJavaError: An error occurred while calling o143.save.
: org.apache.spark.SparkClassNotFoundException: [DATA_SOURCE_NOT_FOUND] Failed to find the data source: com.microsoft.sqlserver.jdbc.spark. Please find packages at `https://spark.apache.org/third-party-projects.html`.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.dataSourceNotFoundError(QueryExecutionErrors.scala:724)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:647)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:697)
	at org.apache.spark.sql.DataFrameWriter.lookupV2Provider(DataFrameWriter.scala:863)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:257)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:248)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.spark.DefaultSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$5(DataSource.scala:633)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$4(DataSource.scala:633)
	at scala.util.Failure.orElse(Try.scala:224)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:633)
	... 16 more

In [44]:
from pyspark.sql import SparkSession

# Define the path to the JDBC driver JAR file
jdbc_driver_path = "Dependencies/sqljdbc_12.6 2/enu/jars/mssql-jdbc-12.6.2.jre8.jar"  # Change this to your actual path

# Initialize Spark session with JDBC driver
spark = SparkSession.builder \
    .appName("Azure SQL Database Interaction") \
    .config("drivers", "com.microsoft.sqlserver.jdbc.SQLServerDriver")\
    .getOrCreate()     #.config("spark.jars", jdbc_driver_path) \

# Replace placeholders with your actual details
sql_engine_name = "retailers"
server_name = "retailers.database.windows.net"
database_name = "consulting_db"
jdbc_url = f"jdbc:sqlserver://{server_name}:1433;database={database_name}"

jdbc_user = "Bos"
jdbc_password = "B@sNat0sh123!"
table_name = "staging.retailer_test"

# Configure connection properties
connection_properties = {
    "driver": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
    "user": jdbc_user,
    "password": jdbc_password,
    "encrypt": "true",
    "trustServerCertificate": "false",
    "hostNameInCertificate": "*.database.windows.net"
}

# Example DataFrame (you should replace this with your actual DataFrame)
data = [("John Doe", 30), ("Jane Doe", 25)]
columns = ["Name", "Age"]
spar_all_df = spark.createDataFrame(data, columns)

# Write data to Azure SQL Database
spar_all_df.write.jdbc(url=jdbc_url, table=table_name, mode="overwrite", properties=connection_properties)

# Stop the Spark session
spark.stop()

Py4JJavaError: An error occurred while calling o416.jdbc.
: java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.sql.execution.datasources.jdbc.DriverRegistry$.register(DriverRegistry.scala:46)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1(JDBCOptions.scala:103)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1$adapted(JDBCOptions.scala:103)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:103)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcOptionsInWrite.<init>(JDBCOptions.scala:254)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcOptionsInWrite.<init>(JDBCOptions.scala:258)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:47)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:859)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:388)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:361)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:248)
	at org.apache.spark.sql.DataFrameWriter.jdbc(DataFrameWriter.scala:756)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)

In [26]:
server = "retailers.database.windows.net"
database_name = "consulting_db"
username = "Bos"
password = "B@sNat0sh123!"
driver = "{ODBC Driver 17 for SQL Server}"
connection_string = f"mssql+pyodbc://{username}:{password}@{server}/{database_name}?driver={driver}"

In [27]:
#Read:
spark = SparkSession.builder \
    .appName("LoadDataToAzureSQL") \
    .config("spark.executor.memory", "6g") \
    .config("spark.driver.memory", "6g") \
    .config("spark.executor.cores", "4") \
    .config("spark.executor.extraJavaOptions", "-XX:+UseG1GC") \
    .config("spark.driver.extraJavaOptions", "-XX:+UseG1GC") \
    .config("spark.jars.packages", "com.crealytics:spark-excel_2.12:0.13.7")\
    .config("spark.driver.extraClassPath","Dependencies/sqljdbc_12.6 2/enu/jars/mssql-jdbc-12.6.2.jre8.jar")\
    .getOrCreate() # .config("spark.sql.shuffle.partitions", "100") \

df = spark.read.format("jdbc") \
    .option("url", connection_string) \
    .option("dbtable", "staging.Test") \
    .option("user", username) \
    .option("password", password) \
    .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver") \
    .load()

df.show(5)

Py4JJavaError: An error occurred while calling o169.load.
: java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.sql.execution.datasources.jdbc.DriverRegistry$.register(DriverRegistry.scala:46)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1(JDBCOptions.scala:103)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1$adapted(JDBCOptions.scala:103)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:103)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:41)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:34)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:346)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)

In [ ]:
#write:
df.write.format("jdbc") \
    .option("url", connection_string) \
    .option("dbtable", "staging.retailer_spar") \
    .option("user", username) \
    .option("password", password) \
    .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver") \
    .mode("overwrite") \
    .save()

In [28]:
import os
os.environ['CLASSPATH'] = "Dependencies/sqljdbc_12.6 2/enu/jars/mssql-jdbc-12.6.2.jre8.jar"
#.config("spark.driver.extraClassPath","Dependencies/sqljdbc_12.6 2/enu/jars/mssql-jdbc-12.6.2.jre8.jar")\

In [29]:


# Replace placeholders with your actual details
sql_engine_name = "retailers"
server_name = "retailers.database.windows.net"
database_name = "consulting_db"
jdbc_url = f"jdbc:sqlserver://{server_name}:1433;database={database_name}"
jdbc_user = "Bos"
jdbc_password = "B@sNat0sh123!"
table_name = "staging.retailer_spar"

# Configure connection properties
connection_properties = {
    "driver": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
    "user": jdbc_user,
    "password": jdbc_password,
    "encrypt": "true",
    "trustServerCertificate": "false",
    "hostNameInCertificate": "*.database.windows.net"
}

#Write to sql:

# Write data to Azure SQL Database
spar_all_df.write.jdbc(url=jdbc_url, table=table_name, mode="overwrite", properties=connection_properties)

# Stop the Spark session
spark.stop()

Py4JJavaError: An error occurred while calling o173.jdbc.
: java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.sql.execution.datasources.jdbc.DriverRegistry$.register(DriverRegistry.scala:46)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1(JDBCOptions.scala:103)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1$adapted(JDBCOptions.scala:103)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:103)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcOptionsInWrite.<init>(JDBCOptions.scala:254)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcOptionsInWrite.<init>(JDBCOptions.scala:258)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:47)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:859)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:388)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:361)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:248)
	at org.apache.spark.sql.DataFrameWriter.jdbc(DataFrameWriter.scala:756)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)

In [11]:
#All connection details
jdbc_user = "Bos" #profmlungu
jdbc_password = "B@sNat0sh123!" #Florence_Wifey
table_name = "staging.retailer_spar"
#jdbc_url = "jdbc:sqlserver://retailers.database.windows.net:1433;database=consulting_db;DatabaseEncryption=yes;Encrypt=true;TrustServerCertificate=False;HostNameInCertificate=*.database.windows.net;LoginTimeout=30;"
#jdbc_url = "jdbc:sqlserver://retailers.database.windows.net:1433;database=consulting_db;user=profmlungu@retailers;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
jdbc_url = f"jdbc:sqlserver://{server_name};database={database_name};user={jdbc_user}@retailers;password={jdbc_password};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"


connection_properties = {
    "user": jdbc_user,
    "password": jdbc_password,
    "driver": "com.microsoft.sqlserver.jdbc.SQLServerDriver"
}

In [18]:
df = spark.read.format("com.microsoft.sqlserver.jdbc.spark") \
    .option("url", jdbc_url) \
    .option("dbtable", "staging.Test") \
    .option("user", jdbc_user) \
    .option("password", jdbc_password) \
    .option('driver', 'com.microsoft.sqlserver.jdbc.SQLServerDriver')\
    .load()
df.show(5)

Py4JJavaError: An error occurred while calling o136.load.
: org.apache.spark.SparkClassNotFoundException: [DATA_SOURCE_NOT_FOUND] Failed to find the data source: com.microsoft.sqlserver.jdbc.spark. Please find packages at `https://spark.apache.org/third-party-projects.html`.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.dataSourceNotFoundError(QueryExecutionErrors.scala:724)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:647)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:697)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:208)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.spark.DefaultSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$5(DataSource.scala:633)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$4(DataSource.scala:633)
	at scala.util.Failure.orElse(Try.scala:224)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:633)
	... 15 more

In [ ]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("AzureSQLReadWrite") \
  .config("spark.jars.packages", "com.microsoft.sqlserver:mssql-jdbc:7.2.2.jre8") \
  .getOrCreate()

In [14]:
df = spark.read.jdbc(url=jdbc_url, table="staging.Test", properties=connection_properties)

# Example: Print the first 5 rows
df.show(5)

Py4JJavaError: An error occurred while calling o122.jdbc.
: java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.sql.execution.datasources.jdbc.DriverRegistry$.register(DriverRegistry.scala:46)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1(JDBCOptions.scala:103)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1$adapted(JDBCOptions.scala:103)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:103)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:41)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:34)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:346)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
	at org.apache.spark.sql.DataFrameReader.jdbc(DataFrameReader.scala:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)

In [12]:
df = spark.read \
  .format("jdbc") \
  .option("url", jdbc_url) \
  .option("dbtable", "staging.Test") \
  .load()

Py4JJavaError: An error occurred while calling o124.load.
: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:315)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$2(JDBCOptions.scala:109)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:109)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:41)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:34)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:346)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)

In [18]:
# Write the data to Azure SQL Database
spar_all_df.write.jdbc(url=jdbc_url, table=table_name, mode="overwrite", properties=connection_properties)

Py4JJavaError: An error occurred while calling o139.jdbc.
: java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.sql.execution.datasources.jdbc.DriverRegistry$.register(DriverRegistry.scala:46)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1(JDBCOptions.scala:103)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1$adapted(JDBCOptions.scala:103)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:103)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcOptionsInWrite.<init>(JDBCOptions.scala:254)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcOptionsInWrite.<init>(JDBCOptions.scala:258)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:47)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:859)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:388)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:361)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:248)
	at org.apache.spark.sql.DataFrameWriter.jdbc(DataFrameWriter.scala:756)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)

In [ ]:

# Write DataFrame to SQL Database table
df.write \
  .format("jdbc") \
  .option("url", jdbc_url) \
  .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver") \
  .option("user", jdbc_user) \
  .option("password", jdbc_password) \
  .option("dbtable", "your_table_name") \
  .mode("append") \
  .save()

In [22]:
retailers = [
    "Spar"
    ,"PNP"
    ,"Checkers"
    #,"Woolworths"
]

In [13]:
# Read the Excel file into a Pandas DataFrame
df_pandas_spar = pd.read_excel(r"SQL_Data/Spar/Copy of Insights Report_Ice Tea_Apr'24.xlsx")
df_pandas_spar.head()

,Month-Yr,Region,Cluster,Barcode,Product - Size,Segment,Brand,Store,Format,Sales (R)\n2024,Sales (R)\n2023,Units\n2024,Units\n2023,Sales\nGwth,Units\nGwth
0,2024-04-01 00:00:00,NR,CL2,7.371861e+11,MOYA KOMBUCHA PINEAPPLE - 500MLT,ICED TEA,OTHER,SAFI SPAR,SPAR,293.79,391.72,21.0,28.0,-0.25,-0.25
1,2024-04-01 00:00:00,NR,CL2,7.371861e+11,MOYA KOMBUCHA PINEAPPLE - 1LTR,ICED TEA,OTHER,SAFI SPAR,SPAR,143.94,263.89,6.0,11.0,-0.454545,-0.454545
2,2024-04-01 00:00:00,NR,CL2,6.001651e+12,EJ S KOMBUCHA RAW - 500MLT,ICED TEA,OTHER,BARCLAY SQUARE SPAR,SPAR,349.86,191.92,14.0,8.0,0.822947,0.75
3,2024-04-01 00:00:00,NR,CL2,6.001651e+12,EJ S KOMBUCHA SPICY - 500MLT,ICED TEA,OTHER,BARCLAY SQUARE SPAR,SPAR,174.93,23.99,7.0,1.0,6.291788,6
4,2024-04-01 00:00:00,NR,CL2,6.001651e+12,EJ S KOMBUCHA BUCHU - 500MLT,ICED TEA,OTHER,BARCLAY SQUARE SPAR,SPAR,174.93,263.89,7.0,11.0,-0.33711,-0.363636

In [15]:
df_pandas_spar.tail(20)

,Month-Yr,Region,Cluster,Barcode,Product - Size,Segment,Brand,Store,Format,Sales (R)\n2024,Sales (R)\n2023,Units\n2024,Units\n2023,Sales\nGwth,Units\nGwth
21347,2024-04-01 00:00:00,LV,CL9,6.009815e+12,KOMBUCHA FRUIT COCKTAIL - 4S,ICED TEA,KOMBUCHA,RIVERSIDE SUPERSPAR,SUPERSPAR,626.64,0.00,21.0,0.0,,
21348,2024-04-01 00:00:00,LV,CL9,6.009815e+12,KOMBUCHA FRUIT COCTAIL - 340MLT,ICED TEA,KOMBUCHA,CROSSINGS SUPERSPAR,SUPERSPAR,129.68,53.94,12.0,6.0,1.404153,1
21349,2024-04-01 00:00:00,LV,CL9,6.009815e+12,KUMBUCHA GREEN TEA - 1.5LTR,ICED TEA,KUMBUCHA,CROSSINGS SUPERSPAR,SUPERSPAR,920.43,181.62,32.0,8.0,4.067889,3
21350,2024-04-01 00:00:00,LV,CL9,6.009815e+12,KUMBUCHA GREEN TEA - 1.5LTR,ICED TEA,KUMBUCHA,RIVERSIDE SUPERSPAR,SUPERSPAR,658.73,0.00,22.0,0.0,,
21351,2024-04-01 00:00:00,LV,CL9,6.009815e+12,KUMBUCHA GREEN TEA - 340MLT,ICED TEA,KUMBUCHA,CROSSINGS SUPERSPAR,SUPERSPAR,149.46,59.94,14.0,6.0,1.493493,1.333333
21352,2024-04-01 00:00:00,LV,CL9,6.009815e+12,KOMBUCHA ORANGE - 500MLT,ICED TEA,KOMBUCHA,CROSSINGS SUPERSPAR,SUPERSPAR,444.18,390.36,32.0,34.0,0.137873,-0.058824
21353,2024-04-01 00:00:00,LV,CL9,6.009815e+12,KOMBUCHA ORANGE - 1.5LTR,ICED TEA,KOMBUCHA,CROSSINGS SUPERSPAR,SUPERSPAR,115.96,204.61,4.0,9.0,-0.433263,-0.555556
21354,2024-04-01 00:00:00,LV,CL9,6.009815e+12,KOMBUCHA ORANGE - 1.5LTR,ICED TEA,KOMBUCHA,RIVERSIDE SUPERSPAR,SUPERSPAR,59.98,0.00,2.0,0.0,,
21355,2024-04-01 00:00:00,LV,CL9,6.009815e+12,KOMBUCHA LEMON - 500MLT,ICED TEA,KOMBUCHA,CROSSINGS SUPERSPAR,SUPERSPAR,607.28,0.00,47.0,0.0,,
21356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21357,Selection Status:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21358,Segment: ICED TEA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21359,"Format: (""SUPERSPAR""|""SPAR""|""KWIKSPAR"")",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21360,Store Status: ACTIVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21361,Region: ALL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21362,Mode: SCAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21363,Ctry: RSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21364,Month-Yr: Apr-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21365,Dimension: 9 of 41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21366,"Measure: Sales Value, Units Sold, Sales Growth...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Read the Excel file into a Pandas DataFrame
df_pandas_pnp = pd.read_excel(r"SQL_Data/PNP/KPITrends_01_02_2024_29_02_2024_to_01_02_2024_29_02_2024_ZA (4).xlsx")
df_pandas_pnp.head()

,Query ID,70fd0090-d7e0-40d3-9e54-01138a3d9229
0,Territory,South Africa
1,Data Sample Size,100%
2,Time,01/02/2024 - 29/02/2024 compared to 01/02/2024...
3,Product,NaN
4,"Edible Grocery Beverages (CSD, Coffee & Juice...",NaN

In [12]:
# Read the excel file
df_pnp = pd.read_excel(r"SQL_Data/PNP/KPITrends_01_02_2024_29_02_2024_to_01_02_2024_29_02_2024_ZA (4).xlsx", sheet_name='KPI Trends')

In [13]:
df_pnp.head()

,Calendar Month/Year,Site Name,Site,Article Name,Article,Customers Select. Per.,Tot. Customers Select. Per.,Customers Pen. Select. Per,Sales Units Select. Per.,Measure,...,Avg Customer Freq. Select. Per,Avg. Customer Spend Select. Per.,Measure.2,Avg. Transaction Spend Select. Per.,Measure.3,Avg. Transaction Units Select. Per,Avg. Unit Price Select. Per,Measure.4,Distribution Select. Per.,% Distribution Select. Per.
0,NaN,Result,NaN,Result,NaN,53932,5026415,1.0730,148898,MIX,...,1.34,45.830002,ZAR,31.230000,ZAR,1.44,21.709999,ZAR,731,100.0
1,202402.0,Result,NaN,Result,NaN,53932,5026415,1.0730,148898,MIX,...,1.34,45.830002,ZAR,31.230000,ZAR,1.44,21.709999,ZAR,731,100.0
2,202402.0,Result,NaN,MANHATTAN ICE TEA PEACH 500ML,102503.0,584,5026415,0.0116,1205,MIX,...,1.16,31.280001,ZAR,25.780001,ZAR,1.25,20.650000,ZAR,179,24.5
3,202402.0,Walmer Park,EC01,MANHATTAN ICE TEA PEACH 500ML,102503.0,3,5026415,0.0001,6,EA,...,1.00,19.120001,ZAR,19.120001,ZAR,1.00,19.120001,ZAR,1,0.6
4,202402.0,Newton Park,EC03,MANHATTAN ICE TEA PEACH 500ML,102503.0,4,5026415,0.0001,4,EA,...,1.00,18.610001,ZAR,18.610001,ZAR,1.00,18.610001,ZAR,1,0.6

In [15]:
# Convert the Pandas DataFrame to a Spark DataFrame
df_spark = spark.createDataFrame(df_pnp)

In [17]:
# Print the Spark DataFrame
df_spark.printSchema()

root
 |-- Calendar Month/Year: double (nullable = true)
 |-- Site Name: string (nullable = true)
 |-- Site: string (nullable = true)
 |-- Article Name: string (nullable = true)
 |-- Article: double (nullable = true)
 |-- Customers Select. Per.: long (nullable = true)
 |-- Tot. Customers Select. Per.: long (nullable = true)
 |-- Customers Pen. Select. Per: double (nullable = true)
 |-- Sales Units Select. Per.: long (nullable = true)
 |-- Measure: string (nullable = true)
 |-- Sales Unit Part. Select. Per: double (nullable = true)
 |-- Net Sales Value Select. Per.: long (nullable = true)
 |-- Measure.1: string (nullable = true)
 |-- Net Sales Value Part. Select. Per.: double (nullable = true)
 |-- Transaction Select. Per.: long (nullable = true)
 |-- Transaction Pen Select Per.: double (nullable = true)
 |-- Tot. Transaction Select. Per.: long (nullable = true)
 |-- Avg Customer Freq. Select. Per: double (nullable = true)
 |-- Avg. Customer Spend Select. Per.: double (nullable = true)
 |-- Measure.2: string (nullable = true)
 |-- Avg. Transaction Spend Select. Per.: double (nullable = true)
 |-- Measure.3: string (nullable = true)
 |-- Avg. Transaction Units Select. Per: double (nullable = true)
 |-- Avg. Unit Price Select. Per: double (nullable = true)
 |-- Measure.4: string (nullable = true)
 |-- Distribution Select. Per.: long (nullable = true)
 |-- % Distribution Select. Per.: double (nullable = true)

In [20]:
from pyspark.sql.types import StructType, StructField

# Get the Spark dataframe schema
schema = df_spark.schema

# Convert the Spark schema to a Python structfield schema
python_schema = StructType([StructField(field.name, field.dataType, field.nullable) for field in schema.fields])

# Print the Python structfield schema
print(python_schema)

StructType([StructField('Calendar Month/Year', DoubleType(), True), StructField('Site Name', StringType(), True), StructField('Site', StringType(), True), StructField('Article Name', StringType(), True), StructField('Article', DoubleType(), True), StructField('Customers Select. Per.', LongType(), True), StructField('Tot. Customers Select. Per.', LongType(), True), StructField('Customers Pen. Select. Per', DoubleType(), True), StructField('Sales Units Select. Per.', LongType(), True), StructField('Measure', StringType(), True), StructField('Sales Unit Part. Select. Per', DoubleType(), True), StructField('Net Sales Value Select. Per.', LongType(), True), StructField('Measure.1', StringType(), True), StructField('Net Sales Value Part. Select. Per.', DoubleType(), True), StructField('Transaction Select. Per.', LongType(), True), StructField('Transaction Pen Select Per.', DoubleType(), True), StructField('Tot. Transaction Select. Per.', LongType(), True), StructField('Avg Customer Freq. Select. Per', DoubleType(), True), StructField('Avg. Customer Spend Select. Per.', DoubleType(), True), StructField('Measure.2', StringType(), True), StructField('Avg. Transaction Spend Select. Per.', DoubleType(), True), StructField('Measure.3', StringType(), True), StructField('Avg. Transaction Units Select. Per', DoubleType(), True), StructField('Avg. Unit Price Select. Per', DoubleType(), True), StructField('Measure.4', StringType(), True), StructField('Distribution Select. Per.', LongType(), True), StructField('% Distribution Select. Per.', DoubleType(), True)])

In [11]:
# Read the Excel file into a Pandas DataFrame
df_pandas_ww = pd.read_excel(r"SQL_Data/Woolworths/WW BOS sales FY23-24 April.xlsx")
df_pandas_ww.head()

,Location,10 - CORPORATE,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Supplier,11886 - BOS BRANDS (PTY) LTD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41 - ICE TEA 200ML,0.0
3,NaN,NaN,APR 24,NaN,NaN,NaN,NaN,NaN,NaN,6001240228876 - 330ml Lipton Lemon T - 644304,0.0
4,43 - ICE TEA 330ML,6009881007706 - 300ML BOS PEACH ICED - 644333,241031.94,NaN,NaN,April Grand Total,3180329.43,NaN,NaN,6001240228913 - 330ml Lipton Peach T - 644305,0.0

In [ ]:
# Convert the Pandas DataFrame to a Spark DataFrame
df_spark = spark.createDataFrame(df_pandas)

# Print the Spark DataFrame
df_spark.show()

In [3]:
print(table_name)

your_table_name

In [ ]:
# Write the data to Azure SQL Database
df_transformed.write.jdbc(url=jdbc_url, table=table_name, mode="overwrite", properties=connection_properties)

In [ ]:
# Example transformation: Select specific columns
df_transformed = df.select("column1", "column2")